---
- name: install docker packages from distribution\'s repository
  apt: pkg={{ item }} state=latest
  with_items:
    - docker.io
    - python-docker

- name: ensure docker service is enabled and started
  service: name=docker enabled=yes state=started